class ComplexFormattingTestFeature:
    unformatted = '\n'.join([
        'Feature: feature',
        'Single line description',
        'Background:',
        'description',
        'Given background',
        'Scenario: scenario 1',
        'Given step',
        'And step',
        'When step',
        '@tag1 @tag2',
        'Scenario: scenario 2',
        'Multiline',
        'Description',
        'Given step',
        'When step',
        'Then step',
        '* step',
        '* step',
        'Scenario Outline: outline 1',
        'Given <A>',
        'Then <B>',
        'Examples:',
        '|A|B|',
        '|1|2|',
        'Scenario Outline: outline 2',
        '    description',
        'Given <A>',
        '@example1 @example2',
        '@example3',
        'Examples:',
        '|A|',
        '|B|',
        '|C|',
        '|D|',
        'Examples:',
        '|A|',
        '|E|',
        '|F|',
        '|G|',
    ])

    formatted = '\n'.join([
        'Feature: feature',
        '  Single line description',
        '',
        '',
        '    Background:',
        '      description',
        '',
        '        Given background',
        '',
        '',
        '    Scenario: scenario 1',
        '',
        '        Given step',
        '        And step',
        '        When step',
        '',
        '',
        '    @tag1',
        '    @tag2',
        '    Scenario: scenario 2',
        '      Multiline',
        '      Description',
        '',
        '        Given step',
        '        When step',
        '        Then step',
        '        * step',
        '        * step',
        '',
        '',
        '    Scenario Outline: outline 1',
        '',
        '        Given <A>',
        '        Then <B>',
        '',
        '        Examples:',
        '          | A | B |',
        '          | 1 | 2 |',
        '',
        '',
        '    Scenario Outline: outline 2',
        '      description',
        '',
        '        Given <A>',
        '',
        '        @example1',
        '        @example2',
        '        @example3',
        '        Examples:',
        '          | A |',
        '          | B |',
        '          | C |',
        '          | D |',
        '',
        '        Examples:',
        '          | A |',
        '          | E |',
        '          | F |',
        '          | G |',
        '',
    ])
