---
name: Run SNYK scan
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '17 13 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=upgradable --sarif-file-output=snyk.sarif --print-deps
